trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:


- task: AzureCLI@2
  inputs:
     azureSubscription: 'Azure subscription 1(d35f8a06-2ca5-4504-902d-d46a9b25215b)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      docker build -t fntkubelcontainer.azurecr.io/web-game:v1 2048-game
      az acr login -n fntkubelcontainer
      docker push fntkubelcontainer.azurecr.io/web-game:v1

# - task: AzureCLI@2
#   inputs:
#     azureSubscription: 'Towards-AzurePortal'
#     scriptType: 'bash'
#     scriptLocation: 'inlineScript'
#     inlineScript: |
#       docker build -t kubelankascontainerregistry.azurecr.io/web-game:tag 2048-game
#       az acr login -n kubelankascontainerregistry
#       docker push kubelankascontainerregistry.azurecr.io/web-game:tag

- script: cat 01_kubernetes_aks/app-deploy.yaml

- task: Kubernetes@1
  inputs:
  connectionType: 'Azure Resource Manager'
    azureSubscriptionEndpoint: 'Azure subscription 1(d35f8a06-2ca5-4504-902d-d46a9b25215b)'
    azureResourceGroup: 'Kuberntes-Group'
    kubernetesCluster: 'Kubernetes'
    namespace: 'default'
    command: 'apply'
    useConfigurationFile: true
    configuration: '01_kubernetes_aks'
    secretType: 'dockerRegistry'
    containerRegistryType: 'Azure Container Registry'
    azureSubscriptionEndpointForSecrets: 'Azure subscription 1(d35f8a06-2ca5-4504-902d-d46a9b25215b)'
    azureContainerRegistry: 'fntkubelcontainer.azurecr.io'
    forceUpdate: false

# - task: Kubernetes@1
#   inputs:
#     connectionType: 'Azure Resource Manager'
#     azureSubscriptionEndpoint: 'Towards-AzurePortal'
#     azureResourceGroup: 'kubernetes'
#     kubernetesCluster: 'kubernetes'
#     namespace: 'default'
#     command: 'apply'
#     useConfigurationFile: true
#     configuration: '01_kubernetes_aks'
#     secretType: 'dockerRegistry'
#     containerRegistryType: 'Azure Container Registry'
#     azureSubscriptionEndpointForSecrets: 'Towards-AzurePortal'
#     azureContainerRegistry: 'kubelankascontainerregistry.azurecr.io'
#     forceUpdate: false
